spring:
  # Embedded ActiveMQ Configuration Example
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
  # Spring JMS Settings
  jms:
    listener:
      acknowledge-mode: auto
      auto-startup: true
      concurrency: 2
      max-concurrency: 2
    pub-sub-domain: false

